spring.application.name=ims

spring.datasource.url=postgresql://ep-plain-tree-aitwz77n-pooler.c-4.us-east-1.aws.neon.tech/IMS?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_j1ymwLbnBfi9

jwt.secret = "InventoryManagementSystem1234567890"
jwt.access-token-expiration = 3600000
jwt.refresh-token-expiration = 604800000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true